#!/usr/bin/env bash
# displays a phrase indefinitely and "I am invincible!!!" when receiving a sigterm signal
trap "echo "I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
