#!/usr/bin/env bash
# this script will display numbers 1-20
# on iterations 4, 9, and 17, it will display the number followed by the 
# statement "bad luck from" and "China/Japan/Italy" respectively

badLuckC="bad luck from China"
badLuckJ="bad luck from Japan"
badLuckI="bad luck from Italy"
count=1

while [ $count -le 20 ];
do
	echo $count
	count=$((count + 1))
case $count in
4)
	echo $count
	echo "$badLuckC"
	count=$((count + 1));;
9)
	echo $count
	echo "$badLuckJ"
	count=$((count + 1));;
17)
	echo $count
	echo "$badLuckI"
	count=$((count + 1));;
esac
done
